"use server"

import { createClient } from "@/lib/supabase/server"
import { revalidatePath } from "next/cache"
import type { SupabaseClient } from "@supabase/supabase-js"
import type { Database } from "@/types/database"

// Cast to bypass @supabase/ssr ↔ @supabase/supabase-js@2.46 generic mismatch
async function typedClient(): Promise<SupabaseClient<Database>> {
  return (await createClient()) as unknown as SupabaseClient<Database>
}

export async function confirmAppointment(appointmentId: string, _: FormData) {
  const supabase = await typedClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) throw new Error("Unauthorized")

  await supabase
    .from("appointments")
    .update({ status: "confirmed" })
    .eq("id", appointmentId)
    .eq("rep_id", user.id)

  revalidatePath("/dashboard")
}

export async function dismissUrgentLead(leadId: string, _reason: string, _: FormData) {
  // Resets last_contacted_at so the lead exits "stale" state
  // PHASE B plug-in: queue agent action to log dismissal reason
  const supabase = await typedClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) throw new Error("Unauthorized")

  await supabase
    .from("leads")
    .update({ last_contacted_at: new Date().toISOString() })
    .eq("id", leadId)
    .eq("assigned_rep_id", user.id)

  revalidatePath("/dashboard")
}

export async function logQuickCall(leadId: string, _: FormData) {
  // Creates a minimal outbound call record — full modal comes Week 2
  const supabase = await typedClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) throw new Error("Unauthorized")

  const { data: lead } = await supabase
    .from("leads")
    .select("brand_id")
    .eq("id", leadId)
    .eq("assigned_rep_id", user.id)
    .maybeSingle()

  if (!lead) return

  await supabase.from("calls").insert({
    rep_id: user.id,
    lead_id: leadId,
    brand_id: lead.brand_id,
    direction: "outbound",
    source: "crm_quick",
  })

  await supabase
    .from("leads")
    .update({ last_contacted_at: new Date().toISOString() })
    .eq("id", leadId)

  revalidatePath("/dashboard")
}

export async function regenerateAgentSummary(_: FormData) {
  // PHASE B plug-in: trigger Inngest event "agent.summary.regenerate"
  // Phase 1: no-op — summary is generated by 8am cron only
  revalidatePath("/dashboard")
}
